---
settings:
  name: NetApp solutions for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

product-family:
  name: NetApp solutions
  repo: netapp-solutions-family

sidebar:
  entries:
    - title: Solutions for SAP
      url: /index.html
    - section: bp
    - section: backup
    - section: lifecycle
    - section: briefs
    - title: Legal notices
      url: /legal-notices.html


