sidebar:
  entries:
    - title: SAP Solutions
      url: /index.html
    - section: bp
    - section: backup
    - section: lifecycle
    - section: briefs
    - title: NetApp Solutions
      url: https://docs.netapp.com/us-en/netapp-solutions/

homepage:
  tiles:
    - title: Best Practices
      links:
        - title: "What's New"
          url: aimda-whatsnew.html
        - title: "Videos and Demos"
          url: aimda-videos.html
        - title: "Blogs"
          url: aimda-blogs.html

    - title: Backup, Restore, and Disaster Recovery
      links:
        - title: "What's New"
          url: hc-whatsnew.html
        - title: "Videos and Demos"
          url: hc-videos.html
        - title: "Blogs"
          url: hc-blogs.html

    - title: Solution Briefs
      links:
        - title: "What's New"
          url: appsdb-whatsnew.html
        - title: "Videos and Demos"
          url: appsdb-videos.html

    - title: Lifecycle Management
      links:
        - title: "What's New"
          url: dpsec-whatsnew.html

    - title: Other NetApp Solutions
      links:
        - title: NetApp Solutions Content Library
          url: https://docs.netapp.com/us-en/netapp-solutions/
