sidebar:
  entries:
    - title: SAP Solutions
      url: /index.html
    - section: bp
    - section: backup
    - section: lifecycle
    - section: briefs

homepage:
  tiles:
    - title: AI & Modern Data Analytics
      links:
        - title: "What's New"
          summary: Check out the latest AI and Modern Data Analytics solutions
          url: aimda-whatsnew.html
        - title: "NetApp Data Science toolkit"
          summary: Data management toolkit for data scientists and engineers
          url: https://github.com/NetApp/netapp-data-science-toolkit
        - title: "Videos and Demos"
          summary: Short videos / demos for AI and Modern Data Analytics features
          url: aimda-videos.html
        - title: "Blogs"
          summary: Technical blogs highlighting AI and Modern Data Analytics features
          url: aimda-blogs.html
#
    - title: Hybrid Cloud, Virtualization & Containers
      links:
        - title: "What's New"
          summary: Check out the latest Hybrid Cloud, Virtual Desktop and Containers solutions
          url: hc-whatsnew.html
        - title: "Videos and Demos"
          summary: Short videos / demos for Hybrid Cloud, Virtualization and Containers features
          url: hc-videos.html
        - title: "Blogs"
          summary: Technical blogs highlighting Hybrid Cloud, Virtualization and Containers features
          url: hc-blogs.html
#
    - title: Enterprise Applications & Databases
      links:
        - title: "What's New"
          summary: Check out the latest Business Applications & Enterprise Database solutions
          url: appsdb-whatsnew.html
        - title: "Videos and Demos"
          summary: Short videos / demos for Business Applications & Enterprise Database features
          url: appsdb-videos.html
#        - title: "Blogs"
#          summary: Technical blogs highlighting Business Applications & Enterprise Database features
#          url: appsdb-blogs.html
#
    - title: Data Protection & Security
      links:
        - title: "What's New"
          summary: Check out the latest Data Protection & Security solutions
          url: dpsec-whatsnew.html
#        - title: "Videos and Demos"
#          summary: Short videos / demos forData Protection & Security features
#          url: dpsec-videos.html
#        - title: "Blogs"
#          summary: Technical blogs highlighting Data Protection & Security features
#          url: dpsec-blogs.html
#
    - title: Solution Automation
      links:
        - title: "What's New"
          summary: Check out the latest automation capabilities in NetApp solutions
          url: automation-whatsnew.html
        - title: "Videos and Demos"
          summary: Short videos / demos about NetApp solutions automation
          url: automation-videos.html
#        - title: "Blogs"
#          summary: Technical blogs highlighting automation capabilities in NetApp solutions
#          url: automation-blogs.html
        - title: Request Automation
          summary: Want to request new automation?  Fill out the request form here.
          url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Automation]%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20%3Crequest_title%3E
#
    - title: Feedback
      links:
        - title: Propose a New Solution
          summary: Looking for a solution that is not provided?  Give us an overview of the solution you are looking for and request it.
          url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Solution]%0d%0a%0d%0aSolution%20Use%20Case:%20%0d%0aSolution%20Description:%20%0d%0aAdditional%20Comments:&title=Request%20Solution%20-%20%3Csolution%3E
        - title: Provide Solution Feedback
          summary: Have questions or comments about an existing solution?  Give us your feedback on our solution collateral.
          url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Solution%20Feedback]%0d%0a%0d%0aSolution%20Name:%20%0d%0aSolution%20Feedback:%20%0d%0aAdditional%20Comments:&title=Solution%20Feedback%20-%20%3Csolution%3E
