---
settings:
  name: NetApp Solutions SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: SAP Solutions
      url: /index.html
    - section: bp
    - section: backup
    - section: lifecycle
    - section: briefs
    - title: FlexPod SAP Solutions
      url: https://docs.netapp.com/us-en/flexpod/ent-db/index.html
    - title: NetApp Solutions
      url: https://docs.netapp.com/us-en/netapp-solutions/
    - title: Legal Notices
      url: /reference_legal_notices.html


