---
settings:
  name: NetApp Solutions SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    langs: us-en,ja-jp,zh-cn
sidebar:
  entries:
    - title: SAP Solutions
      url: /index.html
    - section: bp
    - section: backup
    - section: lifecycle
    - section: briefs
    - title: NetApp Solutions
      url: https://docs.netapp.com/us-en/netapp-solutions/
    - title: Legal Notices
      url: /reference_legal_notices.html

# homepage:
#  tiles:
#    - title: Best Practices
#      links:
#        - title: "What's New"
#          url: sap-bp-whatsnew.html
#        - title: "Videos and Demos"
#          url: sap-bp-videos.html
#        - title: "Blogs"
#          url: sa-bp-blogs.html
#
#    - title: Backup, Restore, and Disaster Recovery
#      links:
#        - title: "What's New"
#          url: sap-dr-whatsnew.html
#        - title: "Videos and Demos"
#          url: sap-dr-videos.html
#        - title: "Blogs"
#          url: sap-dr-blogs.html
#
#    - title: Solution Briefs
#      links:
#        - title: "What's New"
#          url: sap-sb-whatsnew.html
#        - title: "Videos and Demos"
#          url: sap-sb-videos.html
#
#    - title: Lifecycle Management
#      links:
#        - title: "What's New"
#          url: sap-lcm-whatsnew.html
#
#    - title: Other NetApp Solutions
#      links:
#        - title: NetApp Solutions Content Library
#          url: https:#docs.netapp.com/us-en/netapp-solutions/
