---
sidebar: sidebar
permalink: whats-new.html
keywords: netapp, solutions, sap, sap hana, what's new, updates, change log
summary: Log of recent changes to the NetApp solutions for SAP collateral. 
---
= What's new in NetApp solutions for SAP
:icons: font
:imagesdir: ./media/

[.lead]
Learn what's new in solutions for SAP.

== 02 December 2025
https://docs.netapp.com/us-en/netapp-solutions-sap/backup/hana-sc-generic-scope.html[SAP HANA backup and recovery with SnapCenter^]

This guide provides best practices for SAP HANA data protection with NetApp SnapCenter. The document covers generic and platform-specific SnapCenter configuration and operation guidelines for protecting SAP HANA systems running on the different storage platforms supported by SnapCenter. ONTAP systems, AFF and ASA, Azure NetApp Files, Amazon FSx for ONTAP.

== 12 November 2025
New solution link:https://docs.netapp.com/us-en/netapp-solutions-sap/bp/kvm-hana-introduction.html[SAP HANA with SUSE KVM and NetApp Storage^]:

Deploy SAP HANA Single-Host on SUSE KVM using NetApp storage with SR-IOV network interfaces and NFS or FCP storage access. 

== 18 August 2025
The NetApp Solutions site is now the link:https://docs.netapp.com/us-en/netapp-solutions-family/index.html[NetApp solutions family^], which includes the following sites:

* link:https://docs.netapp.com/us-en/netapp-solutions-ai/index.html[NetApp artificial intelligence solutions^]
* link:https://docs.netapp.com/us-en/netapp-solutions-containers/index.html[NetApp container solutions^]
* link:https://docs.netapp.com/us-en/netapp-solutions-dataops/index.html[NetApp data management solutions^]
* link:https://docs.netapp.com/us-en/netapp-solutions-databases/index.html[NetApp database solutions^]
* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/index.html[NetApp public and hybrid cloud solutions^] 
* NetApp solutions for SAP
* link:https://docs.netapp.com/us-en/netapp-solutions-virtualization/index.html[NetApp virtualization solutions^]
