---
sidebar: sidebar
permalink: backup/hana-sc-vmware-smas-additional-info.html
keywords: SAP HANA, VMware, SnapMirror active sync, SnapCenter, backup and recovery
summary: 
---

= Additional information and version history
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This article provides links to additional resources relevant to this solution.

SnapCenter:

link:hana-br-scs-overview.html[TR-4614: SAP HANA backup and recovery with SnapCenter]

link:hana-sr-scs-system-replication-overview.html[TR-4719: SAP HANA System Replication - Backup and Recovery with SnapCenter]

link:../lifecycle/sc-copy-clone-introduction.html[TR-4667: Automating SAP HANA System Copy and Clone Operations with SnapCenter]

https://docs.netapp.com/us-en/snapcenter/index.html[SnapCenter Software documentation]

SnapMirror active sync:

https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html[SnapMirror active sync overview in ONTAP]

https://knowledge.broadcom.com/external/article?legacyId=83370[NetApp ONTAP with NetApp SnapMirror active sync with VMware vSphere Metro Storage Cluster (vMSC).]

https://docs.netapp.com/us-en/netapp-solutions/vmware/vmware-vmsc-with-smas.html[VMware vSphere Metro Storage Cluster with SnapMirror active sync]

https://www.vmware.com/docs/vmware-vsphere-metro-storage-cluster-vmsc[VMware vSphere Metro Storage Cluster (vMSC)]

Version history:


[width="100%",cols="33%,33%,33%",options="header",]
|===
|Version | Date | Comment 
|Version 1.0 | March 2025 | Initial version
|===