---
sidebar: sidebar
permalink: bp/hana-asa-fc-additional-info.html
keywords:
summary:
---
= Where to find additional information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-20 16:47:33.821615
//

[.lead]
To learn more about the information described in this document, refer to the following documents and/or websites:

* link:../index.html[SAP HANA Software Solutions]
* link:../backup/hana-dr-sr-pdf-link.html[TR-4646: SAP HANA Disaster Recovery with Storage Replication]
* link:../backup/hana-sc-vmware-smas-scope.html[SAP HANA data protection and high availability with SnapCenter, SnapMirror active sync and VMware Metro Storage Cluster^]
* link:../backup/hana-br-scs-overview.html[TR-4614: SAP HANA Backup and Recovery with SnapCenter]
* link:../lifecycle/sc-copy-clone-introduction.html[TR-4667: Automating SAP HANA System Copy and Clone Operations with SnapCenter]

* NetApp Documentation Centers
+
https://www.netapp.com/support-and-training/documentation/[https://www.netapp.com/support-and-training/documentation/^]


* SAP Certified Enterprise Storage Hardware for SAP HANA
+
https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/[https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/^]

* SAP HANA Storage Requirements
+
https://www.sap.com/documents/2024/03/146274d3-ae7e-0010-bca6-c68f7e60039b.html[https://www.sap.com/documents/2024/03/146274d3-ae7e-0010-bca6-c68f7e60039b.html^]
* SAP HANA Tailored Data Center Integration Frequently Asked Questions
+
https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html[https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html^]
* SAP HANA on VMware vSphere Wiki
+
https://help.sap.com/docs/SUPPORT_CONTENT/virtualization/3362185751.html[https://help.sap.com/docs/SUPPORT_CONTENT/virtualization/3362185751.html^]
* SAP HANA on VMware vSphere Best Practices Guide
+
https://www.vmware.com/docs/sap_hana_on_vmware_vsphere_best_practices_guide-white-paper[https://www.vmware.com/docs/sap_hana_on_vmware_vsphere_best_practices_guide-white-paper^]


