---
sidebar: sidebar
permalink: bp/hana-asa-fc-storage-controller-setup_multiple_hosts.html
keywords: storage efficiency, netapp volume encryption, quality of service, qos, fabricpool, Disk shelf, sas, fcp port sets, linux lvm,
summary: This section describes how to create LUNS for a multiple host system
---
== Multiple hosts
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/



[.lead]
This section describes the configuration of the NetApp storage system specific to SAP HANA multiple-hosts systems



== LUN configuration for SAP HANA multiple-host systems

The Linux LVM is being used to increase performance and to address LUN size limitations.

At the SAP HANA host, volume groups and logical volumes need to be created and mounted, as indicated in the following table.

|===
|Logical volume (LV) |Mount point at SAP HANA host |Note

|LV: FC5_data_mnt00001-vol
|/hana/data/FC5/mnt00001
|Mounted using storage connector
|LV: FC5_log_mnt00001-vol
|/hana/log/FC5/mnt00001
|Mounted using storage connector
|LV: FC5_data_mnt00002-vol
|/hana/data/FC5/mnt00002
|Mounted using storage connector
|LV: FC5_log_mnt00002-vol
|/hana/log/FC5/mnt00002
|Mounted using storage connector
|External NFS share: FC5_shared
|/hana/shared
|Mounted at all hosts using NFS and /etc/fstab entry
|===

[NOTE]
SAP HANA multiple-host systems require the `/hana/shared` file system connected to all hosts of a system. Usually this is a NFS share provided by by an NFS server. 
It is recommended to use a high available NFS server e.g. such as an NetApp FAS ot AFF system. Another option is to use the build-in NFS server of a LINUX host for this.

[NOTE]
With the described configuration, the `/usr/sap/FC5` directory in which the default home directory of user FC5adm is stored, is on the local disk for each HANA host. In a disaster recovery setup with disk-based replication, NetApp recommends using four additional LUNs for `/usr/sap/FC5` file system each host so that each database host has all its file systems on the central storage.


[#lun_create]
== Creating LUNs and mapping LUNs to initiator groups

You can use NetApp ONTAP System Manager to create storage volumes and LUNs and the map them to the igroups of the servers and the ONTAP CLI. This guide describes the usage of the CLI.


[NOTE]
The `sanlun` tool is part of the NetApp Host Utilities and must be installed on each SAP HANA host. For more information, see the section "host_setup."


=== Creating LUNs and mapping LUNs to initiator groups using the CLI

This section shows an example configuration using the command line with ONTAP 9 for a 2+1 SAP HANA multiple host system with FC5 FC5 using LVM and two LUNs per LVM volume group:

. Create all LUNs.
+

....
lun create -path FC5_data_mnt00001   -size 1t -ostype linux  -class regular
lun create -path FC5_data2_mnt00001 -size 1t -ostype linux  -class regular
lun create -path FC5_data_mnt00002 -size 1t -ostype linux  -class regular
lun create -path FC5_data2_mnt00002 -size 1t -ostype linux  -class regular
lun create -path FC5_log_mnt00001 -size 260g -ostype linux  -class regular
lun create -path FC5_log2_mnt00001 -size 260g -ostype linux  -class regular
lun create -path FC5_log_mnt00002 -size 260g -ostype linux  -class regular
lun create -path FC5_log2_mnt00002 -size 260g -ostype linux  -class regular
....


. Create the initiator group for all servers belonging to system FC5.
+

....
lun igroup create -igroup HANA-FC5 -protocol fcp -ostype linux -initiator 10000090fadcc5fa,10000090fadcc5fb,10000090fadcc5c1,10000090fadcc5c2,10000090fadcc5c3,10000090fadcc5c4 -vserver svm1
....

. Map all LUNs to created initiator group.
+

....
lun map -path FC5_data_mnt00001  -igroup HANA-FC5
lun map -path FC5_data2_mnt00001  -igroup HANA-FC5
lun map -path FC5_data_mnt00002  -igroup HANA-FC5
lun map -path FC5_data2_mnt00002  -igroup HANA-FC5
lun map -path FC5_log_mnt00001  -igroup HANA-FC5
lun map -path FC5_log2_mnt00001  -igroup HANA-FC5
lun map -path FC5_log_mnt00002  -igroup HANA-FC5
lun map -path FC5_log2_mnt00002  -igroup HANA-FC5
....


