---
sidebar: sidebar
permalink: bp/hana-asa-fc-storage-controller-setup_single_host.html
keywords: storage efficiency, netapp volume encryption, quality of service, qos, fabricpool, Disk shelf, sas, fcp port sets, linux lvm,
summary: This section describes the configuration of the NetApp storage system. You must complete the primary installation and setup according to the corresponding Data ONTAP setup and configuration guides.
---
== Storage controller setup - single host
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/



[.lead]
This section describes the configuration of the NetApp storage system specific to SAP HANA single-host systems


== LUN configuration for SAP HANA single-host systems

The Linux LVM is being used to increase performance and to address LUN size limitations. 
At the SAP HANA host, volume groups and logical volumes need to be created and mounted, as indicated in the following table.

|===
|Logical volume/LUN |Mount point at SAP HANA host |Note

|LV: FC5_data_mnt0000-vol
|/hana/data/FC5/mnt00001
|Mounted using /etc/fstab entry
|LV: FC5_log_mnt00001-vol
|/hana/log/FC5/mnt00001
|Mounted using /etc/fstab entry
|LUN: FC5_shared
|/hana/shared/FC5
|Mounted using /etc/fstab entry
|===

[NOTE]
With the described configuration, the `/usr/sap/FC5` directory in which the default home directory of user FC5adm is stored, is on the local disk. In a disaster recovery setup with disk-based replication, NetApp recommends creating an additional LUN for the `/usr/sap/FC5` directory so that all file systems are on the central storage.



[#lun_create]
== Creating LUNs and mapping LUNs to initiator groups

You can use NetApp ONTAP System Manager to create storage volumes and LUNs and the map them to the igroups of the servers and the ONTAP CLI. This guide describes the usage of the CLI.


[NOTE]
The `sanlun` tool is part of the NetApp Host Utilities and must be installed on each SAP HANA host. For more information, see the section "host_setup."


=== Creating LUNs and mapping LUNs to initiator groups using the CLI

This section shows an example configuration using the command line with ONTAP 9 for a  SAP HANA single  host system with SID FC5 using LVM and two LUNs per LVM volume group:

. Create all LUNs.
+

....
lun create -path  FC5_data_mnt00001   -size 1t -ostype linux  -class regular
lun create -path FC5_data2_mnt00001 -size 1t -ostype linux  -class regular
lun create -path FC5_log_mnt00001 -size 260g -ostype linux  -class regular
lun create -path FC5_log2_mnt00001 -size 260g -ostype linux  -class regular
lun create -path FC5_shared -size 260g -ostype linux  -class regular

....


. Create the initiator group for all servers belonging to system FC5.
+

....
lun igroup create -igroup HANA-FC5 -protocol fcp -ostype linux -initiator 10000090fadcc5fa,10000090fadcc5fb -vserver svm1
....

. Map all LUNs to created initiator group.
+

....
lun map -path FC5_data_mnt00001    -igroup HANA-FC5
lun map -path FC5_data2_mnt00001  -igroup HANA-FC5
lun map -path FC5_log_mnt00001  -igroup HANA-FC5
lun map -path FC5_log2_mnt00001  -igroup HANA-FC5
lun map -path FC5_shared  -igroup HANA-FC5
....


