---
sidebar: sidebar
permalink: bp/saphana_aff_nfs_update_history.html
keywords:
summary:
---

= Update history
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The following technical changes have been made to this solution since its original publication.

[cols=2*,options="header",cols="25,50"]
|===

| Date
| Update summary
| October 2015 | Initial version
| March 2016 | Updated capacity sizing
Updated mount options for `/hana/shared`
Updated sysctl parameter
| February 2017 | New NetApp storage systems and disk shelves
New features of ONTAP 9
Support for 40GbE
New OS releases (SUSE Linux Enterprise Server 12 SP1 and Red Hat Enterprise Linux 7.2)
New SAP HANA release
| July 2017 | Minor updates
 | September 2018 | New NetApp storage systems
Support for 100GbE
New OS releases (SUSE Linux Enterprise Server 12 SP3 and Red Hat Enterprise Linux 7.4)
Additional minor changes
SAP HANA 2.0 SPS3
| October 2019 | New NetApp storage systems and NVMe shelf
New OS releases (SUSE Linux Enterprise Server 12 SP4, SUSE Linux Enterprise Server 15, and Red Hat Enterprise Linux 7.6)
Max data volume size
Minor changes
| December 2019 | New NetApp storage systems
New OS release SUSE Linux Enterprise Server 15 SP1
| March 2020 | Support for nconnect for NFSv3
New OS release Red Hat Enterprise Linux 8
| May 2020 | Support for multiple data volume partitions available with SAP HANA 2.0 SPS4
| June 2020 | Additional information about optional functionalities
Minor updates
| December 2020 | Support for nconnect for NFSv4.1 starting with ONTAP 9.8
New OS releases
New SAP HANA versions
| February 2021 | New NetApp storage systems
Changes in host network settings
Minor changes
| April 2021 | VMware vSphere-specific information added
| September 2022 | New OS-Releases 
| August 2023 | New Storage Systems (AFF C-Series) 
| December 2023 | Update of host setup
Revised nconnect settings
Added information about NFSv4.1 sessions 
| May 2024 | New Storage Systems (AFF A-Series)
| September 2024 | Minor Updates 
| November 2024 | New Storage Systems
|===
